sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '13'

before_script:
  - npm prune
script:
  - npm run test
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
